<?php

$yn = static fn (int $yesScore) => [
    ['label' => 'Ya', 'value' => 'ya', 'score' => $yesScore, 'order' => 1],
    ['label' => 'Tidak', 'value' => 'tidak', 'score' => 0, 'order' => 2],
];

return [
    [
        'code' => 'liver_hep_b_positive',
        'category' => 'hati',
        'dimension' => 'hepatitis_b',
        'text' => 'Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?',
        'type' => 'single_choice',
        'order' => 10,
        'options' => $yn(3),
    ],
    [
        'code' => 'liver_family_hep_b',
        'category' => 'hati',
        'dimension' => 'family_hepatitis_b',
        'text' => 'Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?',
        'type' => 'single_choice',
        'order' => 20,
        'options' => $yn(2),
    ],
    [
        'code' => 'liver_risky_sex',
        'category' => 'hati',
        'dimension' => 'risky_sex',
        'text' => 'Apakah Anda pernah berhubungan seksual berisiko/tanpa pengaman dengan bukan pasangan suami/istri?',
        'type' => 'single_choice',
        'order' => 30,
        'options' => $yn(2),
    ],
    [
        'code' => 'liver_transfusion',
        'category' => 'hati',
        'dimension' => 'transfusion',
        'text' => 'Apakah Anda pernah menerima transfusi darah sebelumnya?',
        'type' => 'single_choice',
        'order' => 40,
        'options' => $yn(1),
    ],
    [
        'code' => 'liver_dialysis',
        'category' => 'hati',
        'dimension' => 'dialysis',
        'text' => 'Apakah Anda pernah menjalani cuci darah atau hemodialisis?',
        'type' => 'single_choice',
        'order' => 50,
        'options' => $yn(2),
    ],
    [
        'code' => 'liver_injection_drugs',
        'category' => 'hati',
        'dimension' => 'injection_drugs',
        'text' => 'Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?',
        'type' => 'single_choice',
        'order' => 60,
        'options' => $yn(3),
    ],
    [
        'code' => 'liver_odhiv',
        'category' => 'hati',
        'dimension' => 'odhiv',
        'text' => 'Apakah Anda adalah orang dengan HIV (ODHIV)?',
        'type' => 'single_choice',
        'order' => 70,
        'options' => $yn(3),
    ],
    [
        'code' => 'liver_hep_c_unhealed',
        'category' => 'hati',
        'dimension' => 'hepatitis_c',
        'text' => 'Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?',
        'type' => 'single_choice',
        'order' => 80,
        'options' => $yn(2),
    ],
    [
        'code' => 'liver_high_cholesterol',
        'category' => 'hati',
        'dimension' => 'cholesterol',
        'text' => 'Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?',
        'type' => 'single_choice',
        'order' => 90,
        'options' => $yn(1),
    ],
];
